<?php

/**
 * Implements hook_menu().
 * @return array
 */
function selectize_menu() {
  $items = array();

  $items['admin/config/content/selectize-js'] = array(
    'title' => 'Selectize.js',
    'description' => 'Administer basic settings for Selectize.js.',
    'access callback' => 'user_access',
    'access arguments' => array('administer selectize'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('selectize_admin_settings'),
    'file' => 'selectize.admin.inc',
  );

  return $items;
}

function selectize_form_alter(&$form, &$form_state, $form_id) {
  $apply_selectize = variable_get('selectize_all', FALSE);

  if ($apply_selectize) {
    $form['#attached']['js'][] = libraries_get_path('selectize') . '/dist/js/standalone/selectize.min.js';
    $form['#attached']['css'][] = libraries_get_path('selectize') . '/dist/css/selectize.css';
    drupal_add_js("jQuery('select').selectize();", array('type' => 'inline', 'scope' => 'footer'));
  }

  $form['testing'] = array(
    '#title' => 'sdfsdfds',
    '#type' => 'selectize',
    '#settings' => array(),
    '#options' => array(),
  );
}

/**
 * Implements template_preprocess_select().
 * @param $variables
 */
function selectize_preprocess_select(&$variables) {

}